### ISSUE TITLE
Fix security vulnerabilities in the server.

### ISSUE THREAD

**Issue by jorgelr617** [antimeme/rotpi#2]
Suspense Date: Next Meetup (July 25th)

**Comment by jorgelr617** [comment]
@antimeme 

Jeff, are you OK with working this issue? If not, please let me know so that it can be assigned to someone else.

**Comment by antimeme** [comment]
Yes, I'm on it.

-- Jeff

**Comment by antimeme** [comment]
Fixed by change b0211f95db5189ea61eb1868e68f402c4ce9954a.
