### ISSUE TITLE
Handle the uncaught exceptions in the Server.

### ISSUE THREAD

**Issue by jorgelr617** [antimeme/rotpi#4]
Suspense Date: Next Meetup (July 25th)

**Comment by jorgelr617** [comment]
@JohnnyRobotic 

Bill, are you OK with working this issue? If not, please let me know so that it can be assigned to someone else.

**Comment by JohnnyRobotic** [comment]
No, not at all.  I wish I was but I don't have any idea where to even start. My programming skills are rudimentary at best.

Bill Sprague

**Comment by jorgelr617** [comment]
@JohnnyRobotic

No problem. I'll assign it to someone else. Have you started the client? Do you need help with the client? Start first with creating an html page where the user can enter inputs into a text area.

**Comment by jorgelr617** [comment]
@mikegomezg 

Mike, can you please work on this bug in the server? Rather than throwing exceptions in the server, print the error to the console in the server and let the server come back to listening.

**Comment by antimeme** [comment]
Change 8b54a414074ab8c4c4b3b89d5db57d5f37580c59 addresses this issue.
